version: '3.9'

services:
  db_test:
    container_name: db_test
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=db_postgres
    image: postgres:16.1-alpine3.18
